### ISSUE TITLE
Error from cisco ASA to fortigate

### ISSUE THREAD

**Issue by gorizon35** [glennake/DirectFire_Converter#13]
Traceback (most recent call last):
  File "converter.py", line 254, in <module>
    main(src_format=args.source, dst_format=args.destination, routing_info=args.routing)
  File "/usr/local/lib/python3.8/dist-packages/traceback_with_variables/print.py", line 98, in wrapper
    return func(*args, **kwargs)
  File "converter.py", line 230, in main
    parsed_data = parse(
  File "converter.py", line 127, in parse
    parsed_data = parse(src_config, routing_info)
  File "/root/DirectFire_Converter/DirectFire/Converter/parsers/ciscoasa.py", line 1585, in parse
    src_interface = interface_lookup(
  File "/root/DirectFire_Converter/DirectFire/Converter/common.py", line 40, in interface_lookup
    ip_address = ipaddress.ip_address(ip_address)
  File "/usr/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'host' does not appear to be an IPv4 or IPv6 address

**Comment by glennake** [comment]
@gorizon35 thanks for raising this issue.

Can you send the log and configuration to glennake [at] live.co.uk so I can take a look?

Thanks

**Comment by glennake** [comment]
@gorizon35 thanks for sharing the log file and config.

I have fixed a couple of issues in commit a419771df21e939bdc0f8bb95a0aa21753295cb2 that should help here.

Worth noting that FortiGate firewall policy generation is not yet fully supported so you won't get a full configuration.

Let me know how it goes now?

Thanks

**Comment by glennake** [comment]
Closing as no response
